(()=>{const $=s=>document.querySelector(s),gallery=$('#gallery');const KEY='ggrid.theme-lab.enabled.v1';let themes=[],docs=new Map(),enabled=new Set(),current=0;
const fallback=['classic','mine','space-station','ancient-temple','ice-cavern','cybergrid','pirate-ship'];
function markup(){return '<div class="board">'+Array.from({length:16},()=>'<i class="cell"></i>').join('')+'<i class="piece ball"></i><i class="piece brick"></i><i class="piece glue1"></i><i class="piece glue2"></i><i class="piece wall"></i><i class="exit"></i></div>'}
function paint(el,t){const c=t.colors||{};for(const [k,v] of Object.entries({wrap:c.wrap||c.background,board:c.board,c1:c.cell1||c.board,c2:c.cell2||c.background,accent:c.accent||'#e3b05b',ball1:c.ball1,ball2:c.ball2,ball3:c.ball3,b1:c.brick1,b2:c.brick2,be:c.brickEdge,w1:c.wall1,w2:c.wall2}))if(v)el.style.setProperty('--'+k,v);el.innerHTML=markup()}
function legend(t){const p=t.pieces||{};return (p.ball?.name||'Golyó')+' · '+(p.brick?.name||'Tégla')+' · '+(p.wall?.name||'Fal')+' · '+(p.exit?.name||'Kijárat')+' · '+(t.abilities?.freeze?.name||'Freeze')}
function save(){localStorage.setItem(KEY,JSON.stringify([...enabled]));$('#count').textContent=enabled.size+' téma engedélyezve az Editor számára';render()}
function render(){gallery.innerHTML='';themes.forEach((m,i)=>{const t=docs.get(m.id),card=document.createElement('article');card.className='card'+(enabled.has(m.id)?' selected':'');card.innerHTML='<div class="card-head"><h2>'+m.name+'</h2><span class="badge">'+(enabled.has(m.id)?'Kiválasztva':'Nincs kiválasztva')+'</span></div><p>'+m.description+'</p><div class="scene"></div><div class="legend">'+legend(t)+'</div><div class="card-actions"><button data-view>Megnyitás</button><button data-toggle>'+(enabled.has(m.id)?'Eltávolítás az Editorból':'Hozzáadás az Editorhoz')+'</button></div>';paint(card.querySelector('.scene'),t);card.querySelector('[data-view]').onclick=()=>open(i);card.querySelector('[data-toggle]').onclick=()=>{enabled.has(m.id)?enabled.delete(m.id):enabled.add(m.id);save()};gallery.append(card)})}
function open(i){current=i;const m=themes[i],t=docs.get(m.id);$('#mName').textContent=m.name;$('#mDesc').textContent=m.description;paint($('#mScene'),t);$('#mLegend').textContent=legend(t);$('#toggle').textContent=enabled.has(m.id)?'✓ Kiválasztva – eltávolítás':'＋ Kerüljön a Scenario Editorba';$('#modal').hidden=false}
$('#close').onclick=()=>$('#modal').hidden=true;$('#prev').onclick=()=>open((current-1+themes.length)%themes.length);$('#next').onclick=()=>open((current+1)%themes.length);$('#toggle').onclick=()=>{const id=themes[current].id;enabled.has(id)?enabled.delete(id):enabled.add(id);localStorage.setItem(KEY,JSON.stringify([...enabled]));render();open(current)};$('#all').onclick=()=>{enabled=new Set(themes.map(x=>x.id));save()};$('#none').onclick=()=>{enabled=new Set();save()};$('#defaults').onclick=()=>{enabled=new Set(themes.map(x=>x.id));save()};
async function init(){const r=await fetch('content/themes/index.json',{cache:'no-cache'}),idx=await r.json();themes=idx.themes||[];await Promise.all(themes.map(async m=>{const q=await fetch('content/themes/'+m.src,{cache:'no-cache'});docs.set(m.id,await q.json())}));try{const a=JSON.parse(localStorage.getItem(KEY)||'null');enabled=new Set(Array.isArray(a)?a:themes.map(x=>x.id))}catch(_){enabled=new Set(fallback)}save()}init().catch(e=>gallery.textContent='Theme Library betöltési hiba: '+e.message)})();