const $=(s,r=document)=>r.querySelector(s), api=async(url,opt={})=>{const r=await fetch(url,opt);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||r.statusText);return r.headers.get('content-type')?.includes('json')?r.json():r};
let themes=[],current=null,tab='overview';
const stages=['MOOD','TARGET','ASSETS','BACKGROUNDS','BUILD','QA','RELEASE'];
async function refresh(){themes=(await api('/api/themes')).themes;renderCatalog();if(current){current=await api('/api/themes/'+current.id);renderProject()}}
function renderCatalog(){const c=$('#catalog');c.innerHTML='';for(const t of themes){const d=document.createElement('div');d.className='theme-card'+(current?.id===t.id?' active':'');d.innerHTML=`<b>${t.name}</b><code>${t.id}</code><small>${t.computedStage}</small>`;d.onclick=async()=>{current=await api('/api/themes/'+t.id);tab='overview';renderCatalog();renderProject()};c.append(d)}}
function stagebar(){const cur=current.computedStage;let passed=true;return stages.map(s=>{let cl='stage ';if(s===cur){cl+='current';passed=false}else if(passed)cl+='done';else cl+='locked';return `<span class="${cl}">${s}</span>`}).join('')}
function renderProject(){const w=$('#workspace');w.innerHTML='';const f=$('#projectTemplate').content.cloneNode(true);$('[data-k=name]',f).textContent=current.name;$('[data-k=id]',f).textContent=current.id;$('[data-k=stagebar]',f).innerHTML=stagebar();$('[data-act=export]',f).onclick=exportProject;f.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>{tab=b.dataset.tab;renderProject()};if(b.dataset.tab===tab)b.style.background='#516b84'});w.append(f);renderPanel()}
function panel(html){$('[data-k=panel]').innerHTML=html}
function promptCard(stage){const p=current.stages[stage]||{prompts:[]},prompts=p.prompts||[];return `<div class="card"><h3>Prompt változatok</h3><div class="prompt-list">${prompts.map(x=>`<div class="prompt"><b>${x.id}</b> · ${x.createdAt}<br>${esc(x.text)}</div>`).join('')||'<span class="warn">Még nincs prompt.</span>'}</div><p><textarea id="promptText" placeholder="Új prompt..."></textarea></p><button id="addPrompt">Prompt mentése</button></div>`}
function uploadCard(stage,label,folder,approved){return `<div class="card"><h3>${label}</h3><div class="drop">${approved?.file?`<img src="/project-file/${current.id}/${approved.file}"><p class="ok">✓ elfogadott: ${approved.file}</p>`:'<p>Nincs elfogadott kép.</p>'}<input type="file" id="fileUp" accept=".png,.jpg,.jpeg,.webp"><button id="uploadFile">Feltöltés</button><div id="uploadStatus"></div></div></div>`}
function renderPanel(){if(tab==='overview')return overview();if(tab==='mood')return stageImage('mood','Hangulatterv','mood');if(tab==='target')return stageImage('target','Render célkép','target');if(tab==='assets')return assets();if(tab==='backgrounds')return backgrounds();if(tab==='build')return build()}
function overview(){panel(`<div class="card"><h3>Pilotprojekt</h3><dl class="meta"><dt>Állapot</dt><dd>${current.computedStage}</dd><dt>Projektverzió</dt><dd>${current.projectVersion}</dd><dt>Strict pipeline</dt><dd>${current.strict?'igen':'nem'}</dd><dt>Leírás</dt><dd>${esc(current.description||'')}</dd></dl></div><div class="card"><h3>Workflow v2</h3><p>A végleges út: hangulatterv → render célkép → <b>egyedi elemek</b> → <b>külön portré/fekvő háttér</b> → build → QA.</p><p>Az elemlapok továbbra is használhatók gyors kísérlethez/legacy forrásként, de a Studio jóváhagyása már az egyedi asseteket tekinti végleges forrásnak.</p></div><div class="card"><h3>Migráció</h3><p>${current.migration?.notes||'Új Theme Studio projekt.'}</p><div id="external"></div></div>`);api('/api/themes/'+current.id+'/external-sources').then(x=>{$('#external').innerHTML='<b>Örökölt források:</b><br>'+x.sources.map(s=>`<code>${s.path}</code> (${Math.round(s.size/1024)} KB)<br>`).join('')})}
function stageImage(stage,title,folder){const s=current.stages[stage];panel(promptCard(stage)+uploadCard(stage,title,folder,s.status==='approved'?s:null)+`<div class="card"><h3>Jóváhagyás</h3><p>Státusz: <b>${s.status}</b></p><button id="approveStage">Aktuális feltöltés elfogadása</button></div>`);$('#addPrompt').onclick=()=>addPrompt(stage);$('#uploadFile').onclick=()=>upload(stage,folder);$('#approveStage').onclick=()=>approve(stage)}
async function addPrompt(stage){const text=$('#promptText').value.trim();if(!text)return;await api('/api/themes/'+current.id+'/prompts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage,text})});await refresh()}
async function upload(stage,folder){const f=$('#fileUp').files[0];if(!f)return;const ext=f.name.match(/\.[^.]+$/)?.[0]||'.png',rel=`${folder}/${Date.now()}${ext}`;await api('/api/themes/'+current.id+'/upload/'+encodeURIComponent(rel),{method:'PUT',body:f});current._lastUpload={stage,file:rel};$('#uploadStatus').innerHTML='<span class="ok">Feltöltve: '+rel+'</span>'}
async function approve(stage){const file=current._lastUpload?.stage===stage?current._lastUpload.file:prompt('Elfogadandó projektfájl relatív útvonala:',current.stages[stage].file||'');if(!file)return;await api('/api/themes/'+current.id+'/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage,file,actor:'Krisztián'})});await refresh()}
function assetLabel(s){
 const names={cell:'Mező',wall:'Fix akadály',ball:'Golyó',brick:'1 cellás mozgó elem',exit:'Kijárat',cue:'Irányjel',freeze:'Freeze jel',rigid:'Gyakori merev test',tileset:'Általános merevtest-anyag',frame:'Pályakeret',zone:'Vezérlősáv',chrome:'UI elem'};
 return names[s.role]||s.role;
}
function assets(){
 const s=current.stages.sheets||{},files=current.assetFiles||{},approved=s.approvedFiles||{},slots=current.themeKitSpec?.slots||[];
 const req=slots.filter(x=>x.required!==false),opt=slots.filter(x=>x.required===false);
 const card=x=>{
  const n=x.id+'.png',f=files[x.id]||{exists:false},a=approved[n],isApproved=!!a&&a.sha256===f.sha256;
  const state=isApproved?'JÓVÁHAGYOTT':f.exists?'FELTÖLTVE':'HIÁNYZIK',cls=isApproved?'ok':f.exists?'warn':'bad';
  return `<div class="drop asset-card"><div class="asset-title"><b>${x.id}</b><small>${assetLabel(x)} · ${x.output?.join('×')||''}</small></div>${f.exists?`<img src="/project-file/${current.id}/${n}?v=${encodeURIComponent(f.sha256||'')}" alt="${x.id}">`:''}<div class="sheet-meta"><span class="${cls}">● ${state}</span>${f.exists?`<br><small>${Math.round((f.size||0)/1024)} KB · ${String(f.sha256||'').slice(0,12)}…</small>`:''}</div><input type="file" data-asset="${x.id}" accept=".png"><button data-upload-asset="${x.id}">${f.exists?'Csere feltöltése':'Feltöltés'}</button></div>`;
 };
 const missing=req.filter(x=>!files[x.id]?.exists);
 panel(promptCard('sheets')+`<div class="card"><h3>Egyedi elemek</h3><p>Minden elem külön PNG-ként kerül be. A képet nem kell egy nagy elemlapról kivágni; így a széleken lévő díszítés, kiálló keret és aszimmetrikus forma sem vágódik le. A háttér lehet átlátszó vagy magenta.</p><p><b>Kötelező elemek:</b> ${req.length} · hiányzik: ${missing.length}</p><div class="asset-grid">${req.map(card).join('')}</div></div>`+`<details class="card"><summary>Opcionális, külön festett gyakori merev testek (${opt.length})</summary><p>Ha nincs külön kép, ezeket az általános rigid anyagminta is kirajzolja.</p><div class="asset-grid">${opt.map(card).join('')}</div></details>`+`<div class="card"><h3>Jóváhagyás</h3><p>Státusz: <b>${s.status}</b> ${s.approvalMode==='individual'?'<span class="ok">· egyedi asset mód</span>':''}</p>${missing.length?`<p class="bad">Még ${missing.length} kötelező egyedi elem hiányzik.</p>`:'<p class="ok">✓ Minden kötelező egyedi elem fel van töltve.</p>'}<button id="approveAssets" ${missing.length?'disabled':''}>Egyedi elemek jóváhagyása</button></div>`);
 $('#addPrompt').onclick=()=>addPrompt('sheets');
 document.querySelectorAll('[data-upload-asset]').forEach(b=>b.onclick=async()=>{const id=b.dataset.uploadAsset,f=document.querySelector('input[data-asset="'+id+'"]').files[0];if(!f)return;try{b.disabled=true;b.textContent='Feltöltés…';await api('/api/themes/'+current.id+'/upload/'+encodeURIComponent(id+'.png'),{method:'PUT',body:f});await refresh()}catch(e){alert('Feltöltési hiba: '+e.message);b.disabled=false}});
 $('#approveAssets').onclick=async()=>{try{await api('/api/themes/'+current.id+'/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage:'sheets',actor:'Krisztián'})});await refresh()}catch(e){alert('Jóváhagyási hiba: '+e.message);await refresh()}};
}
function backgrounds(){
 const s=current.stages.backgrounds||{status:'locked'},files=current.backgroundFiles||{},approved=s.approvedFiles||{};
 const defs=[['bg-portrait.png','Álló háttér','1080×1620'],['bg-landscape.png','Fekvő háttér','1620×1080']];
 const cards=defs.map(([n,label,size])=>{const f=files[n]||{exists:false},ok=!!approved[n]&&approved[n].sha256===f.sha256,state=ok?'JÓVÁHAGYOTT':f.exists?'FELTÖLTVE':'HIÁNYZIK',cls=ok?'ok':f.exists?'warn':'bad';return `<div class="drop background-card"><b>${label}</b><small>${n} · ${size}</small>${f.exists?`<img src="/project-file/${current.id}/${n}?v=${encodeURIComponent(f.sha256||'')}" alt="${label}">`:''}<div class="sheet-meta"><span class="${cls}">● ${state}</span></div><input type="file" data-bg="${n}" accept=".png"><button data-upload-bg="${n}">${f.exists?'Csere feltöltése':'Feltöltés'}</button></div>`}).join('');
 const missing=defs.filter(([n])=>!files[n]?.exists);
 panel(promptCard('backgrounds')+`<div class="card"><h3>Külön háttérképek</h3><p>A háttérképen ne legyen játéktábla, HUD, gomb vagy mozgó elem. A tábla mögötti középső terület legyen nyugodtabb, a széleken lehet részletesebb könyvtár/csillagvizsgáló környezet.</p><div class="background-grid">${cards}</div><p>Státusz: <b>${s.status}</b></p>${missing.length?`<p class="bad">Hiányzik: ${missing.map(x=>x[0]).join(', ')}</p>`:'<p class="ok">✓ Mindkét háttér fel van töltve.</p>'}<button id="approveBackgrounds" ${missing.length?'disabled':''}>Hátterek jóváhagyása</button></div>`);
 $('#addPrompt').onclick=()=>addPrompt('backgrounds');
 document.querySelectorAll('[data-upload-bg]').forEach(b=>b.onclick=async()=>{const n=b.dataset.uploadBg,f=document.querySelector('input[data-bg="'+n+'"]').files[0];if(!f)return;try{b.disabled=true;b.textContent='Feltöltés…';await api('/api/themes/'+current.id+'/upload/'+encodeURIComponent(n),{method:'PUT',body:f});await refresh()}catch(e){alert('Feltöltési hiba: '+e.message);b.disabled=false}});
 $('#approveBackgrounds').onclick=async()=>{try{await api('/api/themes/'+current.id+'/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage:'backgrounds',actor:'Krisztián'})});await refresh()}catch(e){alert('Jóváhagyási hiba: '+e.message);await refresh()}};
}
function build(){const b=current.stages.build,q=current.stages.qa,h=b.history?.at(-1);panel(`<div class="card"><h3>Build</h3><button id="buildBtn">▶ TÉMA ÉPÍTÉSE</button><p>Build státusz: <b>${b.status}</b></p><div class="log">${esc(h?.log||'Még nincs build.')}</div></div><div class="card"><h3>QA</h3><p>Státusz: <b>${q.status}</b></p>${h?.qaDir?`<p>QA mappa: <code>${h.qaDir}</code></p><div class="qa-preview"><img src="/project-file/${current.id}/${h.qaDir}/compare.png?v=${current.projectVersion}" onerror="this.style.display='none'" alt="Target és valódi játék összehasonlítása"></div>`:''}<button id="qaApprove" ${q.status!=='review'?'disabled':''}>✓ TÉMA ELFOGADÁSA</button></div>`);$('#buildBtn').onclick=async()=>{try{await api('/api/themes/'+current.id+'/build',{method:'POST'});await refresh()}catch(e){alert(e.message);await refresh()}};$('#qaApprove').onclick=async()=>{await api('/api/themes/'+current.id+'/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage:'qa',actor:'Krisztián'})});await refresh()}}
async function exportProject(){const r=await fetch('/api/themes/'+current.id+'/export',{method:'POST'});if(!r.ok){let e={};try{e=await r.json()}catch{};return alert('Export hiba: '+(e.error||r.statusText))}const b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=r.headers.get('content-disposition')?.match(/filename="([^"]+)/)?.[1]||current.id+'.ggrid-theme-project';a.click();URL.revokeObjectURL(a.href)}
$('#newBtn').onclick=async()=>{const name=prompt('Téma neve:');if(!name)return;const id=prompt('Theme ID:');if(!id)return;await api('/api/themes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,id,strict:true})});await refresh()}
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async()=>{const f=$('#importFile').files[0];if(!f)return;try{current=await api('/api/import',{method:'POST',body:f});tab='overview';await refresh()}catch(e){alert('Import hiba: '+e.message)}}
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
refresh();
